version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn tslint
      - run:
          name: Test
          command: yarn test
      - run:
          name: code-coverage
          command: yarn coverage
      - store_artifacts:
          path: reports/coverage
          prefix: coverage
      - store_test_results:
          path: reports